### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DerMika** [bariton3/mqseries-php#5]
Hi, 

This library is obviously a copy of my library https://github.com/amabnl/php-mqseries, but for some reason you didn't fork it.

I've open sourced my library under the Apache2 license, which means copyright remains with us. I don't think you're allowed to redistribute it under the MIT license just like that. 

Can you please change the license to Apache2 and attribute copyright to Amadeus benelux in your docs?

**Comment by bariton3** [comment]
Hi DerMika,
I did that you write.

**Comment by DerMika** [comment]
Thanks
